# Installing dependencies:
- brewfile:
    - brew/Brewfile

- shell:
  -
    command: bash -l './scripts/configure_iterm.sh'
    description: Installing fish iTerm integration
    stdout: true
    stderr: true


