- link:
    # omf
    ~/.config/omf: config/omf/
    # wtf
    ~/.config/wtf: config/wtf/
    # fish shell
    ~/.config/fish/config.fish:
      path: config/fish/config.fish
    ~/.config/fish/conf.d:
      path: config/fish/conf.d/*.fish
      glob: true
    ~/.config/fish/functions:
      path: config/fish/functions/*.fish
      glob: true



