- defaults:
    link:
        relink: true
        create: true
        force: true
    shell:
        stdout: true
        stderr: true

- create:
    - $HOME/.config
    - $HOME/dev

- clean:
    $HOME:
        force: true
    $HOME/.config:
        recursive: true
        exclude: $HOME/.config/fish/.iterm2_shell_integration.fish
